version: '3.8'

services:
  srvdb:
    image: postgres
    restart: always
    container_name: srvdb
    hostname: srvdb
    environment:
      POSTGRES_USER: practicaDocker
      POSTGRES_PASSWORD: root
      POSTGRES_DB: practicaD
      TZ:  America/Guayaquil
    ports:
      - 1234:5432
    volumes:
       - db:/var/lib/postgresql/data

  srvwildfly:
    image: sd/practicarestdocker
    container_name: srvwildfly
    hostname: srvwildfly
    environment:
      TZ:  America/Guayaquil
    ports:
      - 8082:8080
      - 8899:8009
      - 9992:9990
      - 8787:8787
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -c standalone.xml -bmanagement 0.0.0.0 --debug *:8787
    depends_on:
      - srvdb
    networks:
      - datalogger_net

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@jasoft.ec
      PGADMIN_DEFAULT_PASSWORD: clave
      TZ:  America/Guayaquil
    ports:
      - 5050:80
    depends_on:
      - srvdb
    networks:
      - datalogger_net
  
volumes:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:/Users/braya/db
      
      
networks:
  datalogger_net: